-- ============================================================
-- Migration 073: Driver pay line source tracking
-- ============================================================
--
-- Adds structured "where did this line come from" fields to
-- order_driver_pay_lines so the UI can:
--   1. Visually distinguish auto-applied from manually added lines
--   2. Let the user click an auto line to jump to the charge profile
--      that produced it
--
-- Prior to this, the only marker was notes = '[auto-applied] …' which
-- is a brittle string match and carries no link back to the profile.
--
-- source_type values:
--   'driver_tariff' — generated by a matching driver tariff
--   'auto_add'      — generated by a standalone auto-add profile
--   NULL            — manually added by a dispatcher (default)
-- ============================================================

BEGIN;

ALTER TABLE order_driver_pay_lines
  ADD COLUMN IF NOT EXISTS source_type TEXT,
  ADD COLUMN IF NOT EXISTS source_tariff_id UUID,
  ADD COLUMN IF NOT EXISTS source_charge_profile_id UUID;

-- Foreign keys wired separately so the migration stays idempotent and
-- doesn't fail if a column already exists without the FK.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'fk_driver_pay_source_tariff'
  ) THEN
    ALTER TABLE order_driver_pay_lines
      ADD CONSTRAINT fk_driver_pay_source_tariff
      FOREIGN KEY (source_tariff_id) REFERENCES driver_tariffs(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'fk_driver_pay_source_charge_profile'
  ) THEN
    ALTER TABLE order_driver_pay_lines
      ADD CONSTRAINT fk_driver_pay_source_charge_profile
      FOREIGN KEY (source_charge_profile_id) REFERENCES driver_charge_profiles(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'chk_driver_pay_source_type'
  ) THEN
    ALTER TABLE order_driver_pay_lines
      ADD CONSTRAINT chk_driver_pay_source_type
      CHECK (source_type IS NULL OR source_type IN ('driver_tariff', 'auto_add'));
  END IF;
END $$;

-- Index for "which lines did this profile generate" reverse lookups
CREATE INDEX IF NOT EXISTS idx_driver_pay_source_profile
  ON order_driver_pay_lines(source_charge_profile_id)
  WHERE source_charge_profile_id IS NOT NULL;

-- Reload PostgREST schema cache so the new columns are available to the API
-- without a manual restart.
NOTIFY pgrst, 'reload schema';

COMMIT;
